#!/usr/bin/env python3

# Copyright (c) 2018 Jonathan Anderson
# All rights reserved.
#
# This software was developed by BAE Systems, the University of Cambridge
# Computer Laboratory, and Memorial University under DARPA/AFRL contract
# FA8650-15-C-7558 ("CADETS"), as part of the DARPA Transparent Computing
# (TC) research program.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

import argparse
import instructions
import os
import sys


def opcodes(args):
    """
    Generate (and validate) a list of instructions, given arguments that can
    include `--all` or a list of opcodes.
    """

    instrs = instructions.instructions

    if args.all:
        return ( (op,) + instrs[op] for op in sorted(instrs.keys()) )
    else:
        return ( (op,) + instrs[op] for op in args.instruction )


def print_pseudocode(args):
    """
    Print the pseudocode for a set of instructions, either to stdout or to a
    set of files in a specified directory.
    """

    import inspect

    if args.output != '-':
        try:
            os.mkdir(args.output)
        except FileExistsError:
            # It's OK if the directory already exists
            pass

        sys.stdout.write("Writing to '%s':" % args.output)

    for (opcode, f, encoding_name) in opcodes(args):
        if args.output == '-':
            out = sys.stdout
        else:
            sys.stdout.write(' %s' % opcode)
            out = open(os.path.join(args.output, '%s.py' % opcode), 'w')

        out.write('#\n# %s: encoding %s\n#\n' % (opcode, encoding_name))
        out.write('%s\n' % inspect.getsource(f))


def print_script(args):
    """
    Pretty-print a DIF instruction stream, including line numbers from the
    source file and a named interpretation of the positional operands.
    """

    import parsing

    filename = args.source
    if not os.path.isfile(filename):
        sys.stderr.write("Error: '%s' is not a file\n" % filename)
        sys.exit(1)

    out = sys.stdout if args.output == '-' else open(args.output, 'w')

    with open(filename, 'r') as f:
        line_number = 0

        for line in f:
            line_number += 1
            src = (filename, line_number)

            out.write('%6d  ' % line_number)
            out.write('%-16s' % line.rstrip())

            (opcode, operands) = parsing.parse(line, src)

            if opcode:
                (f, encoding_name) = instructions.instructions[opcode]
                encoding = instructions.encodings[encoding_name]
                named = parsing.decode(opcode, operands, encoding, src)

                out.write("# Encoding '%s': " % encoding_name)
                out.write(', '.join(['%3s=%d' % (k, v) for (k, v) in named]))

            out.write('\n')


arg_parser = argparse.ArgumentParser(description='''Prints DIF instructions.

This tool can be used to print pseudocode for DIF instructions or textual DIF
representations of a DIF instruction stream.
''')

subparsers = arg_parser.add_subparsers(title='things we can print',
                                       help='what we want to pretty-print')

pseudocode = subparsers.add_parser('pseudocode')
pseudocode.add_argument('-a', '--all', action='store_true',
                        help='Print pseudocode for all instructions')
pseudocode.add_argument('-o', '--output', default='-',
                        help='Output directory for source files')
pseudocode.add_argument('instruction', nargs='*',
                        help='Instructions to print (if not --all)')
pseudocode.set_defaults(func=print_pseudocode)

script = subparsers.add_parser('script')
script.add_argument('-o', '--output', default='-', help='Output file')
script.add_argument('source', help='Script file to print')
script.set_defaults(func=print_script)

try:
    args = arg_parser.parse_args()
    f = args.func

except:
    arg_parser.print_help()
    sys.exit(1)

f(args)
